version: '3.9'
services:
  api:
    build: ./api
    env_file: .env
    ports:
      - "8000:8000"
  web:
    build: ./web
    env_file: .env
    ports:
      - "5173:5173"
  proxy:
    image: nginx:alpine
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - web
